---
- name: Prepare Mock Server
  hosts: mock_server
  become: true
  tasks:
    - name: Start mock server
      raw: "nohup java -Dfile.encoding=UTF-8 -cp /mockserver-netty-jar-with-dependencies.jar:/libs/* -Dmockserver.propertyFile=/mockserver.properties org.mockserver.cli.Main -serverPort 1080 </dev/null >/dev/null 2>&1 & sleep 1"
      changed_when: false

- name: Set Expectations
  hosts: mock_server
  connection: local
  gather_facts: false
  tasks:
    - name: Reset mock server expectations
      uri:
        url: "https://{{ inventory_hostname }}:1080/mockserver/reset"
        method: PUT
        status_code: 200
        headers:
          Content-Type: application/json
        validate_certs: false

    - name: Create gateway api PUT expectation
      uri:
        url: "https://{{ inventory_hostname }}:1080/mockserver/expectation"
        method: PUT
        body:
          httpRequest:
            method: "PUT"
            path: "/api/v1/services/environments/production/gateways/www.example.com"
          httpResponse:
            statusCode: 202
            body:
              currentStatus:
                ingress:
                  placement:
                    instanceRefs:
                      - links:
                          rel: "/api/v1/infrastructure/locations/unspecified/instances/instance1.example.com"
                          name: instance1.example.com
                        ref: "/infrastructure/locations/unspecified/instances/instance1.example.com"
                  tls:
                    certRef:
                      links:
                        rel: "/api/v1/services/environments/production/certs/www.example.com"
                        displayName: www.example.com
                        name: www.example.com
                      ref: "/services/environments/production/certs/www.example.com"
                    protocols:
                      - TLSv1.3
                      - TLSv1.2
                  uris:
                    http://www.example.com: {}
                    https://www.example.com: {}
                state:
                  selfConfigState:
                    configured: 0
                    configuring: 1
                    deleting: 0
                    error: 0
                    isConfigured: false
                    isConfiguring: true
                    isDeleting: false
                    isError: false
                    total: 1
              desiredState:
                ingress:
                  placement:
                    instanceRefs:
                      - links:
                          rel: "/api/v1/infrastructure/locations/unspecified/instances/instance1.example.com"
                          name: instance1.example.com
                        ref: "/infrastructure/locations/unspecified/instances/instance1.example.com"
                  tls:
                    certRef:
                      links:
                        rel: "/api/v1/services/environments/production/certs/www.example.com"
                        displayName: www.example.com
                        name: www.example.com
                      ref: "/services/environments/production/certs/www.example.com"
                    protocols:
                      - TLSv1.3
                      - TLSv1.2
                  uris:
                    http://www.example.com: {}
                    https://www.example.com: {}
              metadata:
                createTime: "2021-09-14T22:18:25Z"
                description: Public gateway for for Example-One
                displayName: First Example Gateway
                kind: gateways
                links:
                  rel: "/api/v1/services/environments/production/gateways/www.example.com"
                name: www.example.com
                uid: 5f33ff4f-6552-4e09-ab34-996ca1e900e6
                updateTime: "2021-09-14T22:18:25Z"

        status_code: 201
        body_format: json
        headers:
          Content-Type: application/json
        validate_certs: false

    - name: Create gateway api GET expectation
      uri:
        url: "https://{{ inventory_hostname }}:1080/mockserver/expectation"
        method: PUT
        body:
          httpRequest:
            method: "GET"
            path: "/api/v1/services/environments/production/gateways/www.example.com"
          httpResponse:
            statusCode: 200
            body:
              currentStatus:
                ingress:
                  placement:
                    instanceRefs:
                      - links:
                          rel: "/api/v1/infrastructure/locations/unspecified/instances/instance1.example.com"
                          name: instance1.example.com
                        ref: "/infrastructure/locations/unspecified/instances/instance1.example.com"
                  tls:
                    certRef:
                      links:
                        rel: "/api/v1/services/environments/production/certs/www.example.com"
                        displayName: www.example.com
                        name: www.example.com
                      ref: "/services/environments/production/certs/www.example.com"
                    protocols:
                      - TLSv1.3
                      - TLSv1.2
                  uris:
                    http://www.example.com: {}
                    https://www.example.com: {}
                state:
                  selfConfigState:
                    configured: 1
                    configuring: 0
                    deleting: 0
                    error: 0
                    isConfigured: true
                    isConfiguring: false
                    isDeleting: false
                    isError: false
                    total: 1
              desiredState:
                ingress:
                  placement:
                    instanceRefs:
                      - links:
                          rel: "/api/v1/infrastructure/locations/unspecified/instances/instance1.example.com"
                          name: instance1.example.com
                        ref: "/infrastructure/locations/unspecified/instances/instance1.example.com"
                  tls:
                    certRef:
                      links:
                        rel: "/api/v1/services/environments/production/certs/www.example.com"
                        displayName: www.example.com
                        name: www.example.com
                      ref: "/services/environments/production/certs/www.example.com"
                    protocols:
                      - TLSv1.3
                      - TLSv1.2
                  uris:
                    http://www.example.com: {}
                    https://www.example.com: {}
              metadata:
                createTime: "2021-09-14T22:18:25Z"
                description: Public gateway for for Example-One
                displayName: First Example Gateway
                kind: gateways
                links:
                  rel: "/api/v1/services/environments/production/gateways/www.example.com"
                name: www.example.com
                uid: 5f33ff4f-6552-4e09-ab34-996ca1e900e6
                updateTime: "2021-09-14T22:18:25Z"
        status_code: 201
        body_format: json
        headers:
          Content-Type: application/json
        validate_certs: false
